name: WDIO tests w/ docker
on:
  push:
    branches:
      - 'master'

jobs: 
  docker-wdio-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create docker image
        run: docker build -t local ./

      - name: Run container
        run: docker run -d --name telnyxtests local 

      - name: Get reports from container
        run: docker cp telnyxtests:/usr/app/tests/reports ./

      - name: Upload Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: allure-results
          path: ./reports

      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: ./reports      
            
      - name: Push to another branch
        if: always()
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docker_reports # The branch name where you want to push the assets
          FOLDER: ./reports # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Reports added" # The commit message 
